### ISSUE TITLE
Can't Run .js Code

### ISSUE THREAD

**Issue by Olgethorpe** [coinbase/gdax-tt#231]
I am following the GDAX Trading Toolkit User's Guide (0.0.1 : https://coinbase.github.io/gdax-tt/gtt_installation.html) and I am able to install the package using yarn and I do not get any error messages in regards to installation, however when I try to test the require statement when running my .js file I get this error:

PATH_TO_DIRECTORY/node_modules/ccxt/js/base/Exchange.js:337
let partial = async params => this[methodName] (url, type, uppercaseMethod, params || {})
                                        ^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (PATH_TO_DIRECTORY/node_modules/ccxt/ccxt.js:33:19)

According the the User's Guide I was able to test the installation since this command:

./node_modules/.bin/gdaxConsole  --product BTC-USD -t

returned what was expected. But when I run my .js file I receive that error as shown above. What can I do to fix this? Thanks!

**Comment by fb55** [comment]
Thanks @kroitor!
