### ISSUE TITLE
Tutorial one fails to run. SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by JamesMcMurran** [coinbase/gdax-tt#37]
This command works for me.
$ ts-node src/consoles/gdaxConsole.ts --product BTC-USD -t

But when i try to run 
$ ts-node tutorials/t001_feeds.ts

I get"
/home/NAME/node_modules/ccxt/ccxt.js:423
                    let partial = async params => this[methodName] (url, type, uppercaseMethod, params)
                                        ^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/NAME/node_modules/gdax-trading-toolkit/src/exchanges/ccxt/index.ts:15:1)
"

Any ideas as to why this is happening?

**Comment by kroitor** [comment]
Hi! You probably have Node version < 7.6+. If that is the case, try updating it. It complains about the modern JS syntax, older versions of Node just don't understand it.

**Comment by JamesMcMurran** [comment]
Yep, that's it TY =). I thought I had updated already from 4 to 6 but I guess it needed to be 8.

**Comment by CjS77** [comment]
Thanks for pointing that out @kroitor. The docs have been updated to reflect the Node 7.6+ dependency
